- .circleci/config.yml
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
* Primarily a fix for over-zealous check on issuer URL in JWTs
* Also upgrades to the circle 1.1.1 orb to resolve the missing less installer
* Also tidies some of the yaml properties
> PAT-1009 Remove JWT issuer check, upgrade orb to 1.1.1. and tidy SQS properties in yaml file.

- README.md
- helm_deploy/prisoner-offender-search/templates/housekeeping-cronjob.yaml
- helm_deploy/prisoner-offender-search/templates/ingress.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/config/JmsConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/config/ResourceServerConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerIndexResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/IndexQueueService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/IndexStatusService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/QueueIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerIndexResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/IndexQueueStatusTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/IndexStatusServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/health/HealthCheckIntegrationTest.kt
This applies the same solution previously used in `probation-offender-seearch-indexer`
> DT-1121 automatically complete build

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/GlobalSearchResource.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/GlobalSearchResourceTest.kt
Count is a reserved word in App Insights logs
> DT-1793 bad custom dimension

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/config/JmsConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/config/JmsLocalStackConfig.kt
And register queues in main config
> DT-2215 Switch from deprecated API

- docker-compose.yml
- helm_deploy/values-dev.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/RestrictedPatientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/dto/RestrictivePatient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/health/RestrictedPatientsApiHealth.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/integration/IntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/integration/wiremock/MockServers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/health/HealthCheckIntegrationTest.kt
- src/test/resources/application-test.yml
- add in health check for restricted patients
- add in basic service and config for talking to the restricted patients api
> NN-3467: (Please don't merge)

- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/QueueIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/EstablishmentSearchResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerSearchByPrisonerNumbersResourceTest.kt
Added a loadPrisoners() that loads specific prisoners based on a pre-determined template.\
Currently just name, and prison is a variable - but this will be enhanced when required
> SDI-248-IntegrationTestImprovement

- docker-compose-localstack-tests.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonersInPrisonService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonersInPrisonResourceTest.kt
Just some tests to show the order is not by score but name
> Sdi 254 name search

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonersInPrisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/SearchOperations.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonersInPrisonResourceTest.kt
`ALEXANDRA` can be matched with ……`ALEX NDR`
Also fix names with punctuation; e.g. double barrel names
> SDI-254 Allow middle wildcard search 

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/dto/RestrictivePatient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexServiceTest.kt
> SDI-271 Remove unused field

- build.gradle.kts
- helm_deploy/prisoner-offender-search/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/PrisonerOffenderSearch.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/config/DiffProperties.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventEmitter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/integration/IntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventsEmitterIntTest.kt
- src/test/resources/application-test.yml
Not currently wired up so doesn't do anything.
> SDI-287 Add service to produce Prisoner Difference events

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventEmitter.kt
The fact this attribute is missing seems to be stopping it from appearing on offender-events-ui.
Strangley I'm unable to write an integration test for the fix so I want to see if it works on dev.
> SDI-287 Send event type message attribute

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerEventHashRepository.kt
- src/main/resources/db/migration/V1_1__prisoner_event_sent.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerEventHashRepositoryTest.kt
> SDI-287 Add method to track prisoner event hashes

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
* Remove details from telemetry so that it matches the events (shows only categories that have changed)
* Turn on telemetry and events in pre and prod
> SDI-287 prisoner diff events

- helm_deploy/prisoner-offender-search/Chart.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Transfer sqs and rds alerts to syscon channel
> Sdi 401 sqs alerts not triggering

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerMovementsEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerMovementsEventServiceTest.kt
TODO a better end to end integration test
> SDI-301 A few more receive scenarios to complete IN movements

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventEmitter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerMovementsEventService.kt
- src/main/resources/documentation/service-description.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventsEmitterIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerMovementsEventServiceTest.kt
TODO releases when not in prison (e.g after a court appearance
> SDI-301 Added main release scenarios

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
> SDI-419 Improve Elastic Search Indexing

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/CurrentIncentive.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/translator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/IncentivesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/MessageIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/integration/wiremock/MockServers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/TranslatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/IncentivesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerSyncServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
This is a dynamic field and can not be cached in elastic search
> SDI-452 Removed days since last review

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventEmitter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/AlertsUpdatedEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerMovementsEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventsEmitterIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventsEmitterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/AlertsUpdatedEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerMovementsEventServiceTest.kt
- src/test/resources/messages/offenderAlertsChanged.json
* raise new event any time the list of alerts change
> SDI-459 prisoner-offender-search.prisoner.alerts-updated event

- helm_deploy/prisoner-offender-search/values.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/IncentivesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/IncentivesServiceTest.kt
Off in prod and preprod, on by default
> SDI-452 feature switch incentives reindex

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/translator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/TranslatorTest.kt
In preparation of allowing greater resilience when a secondary service fails during reindexing
> SDI-452 minor refactor

- .circleci/config.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerEventHashRepository.kt
- src/main/resources/db/migration/V1_4__prisoner_event_sent.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerEventHashRepositoryTest.kt
> SDI-525 Remove all debug for events not raised issue

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/Prisoner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/translator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerDetailResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerDetailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/QueueIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/TranslatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerDetailResourceTest.kt
- src/test/resources/mappings/getBooking_A1090AA.json
- src/test/resources/mappings/getBooking_A7090BB.json
- SDI-603: ✨ Add default responses to reduce wiremock errors
- SDI-603: ✨ Tidy up tests and only index centimetres
> SDI-603: ✨ Tidy up tests and only index centimetres

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/GlobalSearchResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/GlobalSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/NomisService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/SearchClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/GlobalSearchResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/GlobalSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/MatchServiceTest.kt
> SDI-493 Alert if size of index does not match the number of prisone in NOMIS

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PhysicalDetailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/dto/PhysicalDetailRequest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/QueueIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PhysicalDetailResourceTest.kt
- SDI-603: ✨ Index by physical marks
- SDI-603: ✨ Search by physical marks
> SDI-603: ✨ Search by physical marks

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PhysicalDetailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PhysicalDetailResourceTest.kt
- SDI-603: ✨ Search by physical marks
- SDI-603: ✨ Validate shoe size
> SDI-603: ✨ Validate shoe size

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/GlobalSearchResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/GlobalSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/SearchClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/GlobalSearchResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/GlobalSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/MatchServiceTest.kt
> Sdi 493 alert if size of index does not match the number of prisoners in nomis

- helm_deploy/prisoner-offender-search/values.yaml
To see if this helps with OOM errors
> SDI-632 increase resources

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerIndexResource_compareIndexTest.kt
> SDIT-564 Prisoner search should update when prison structure changes

- src/main/resources/documentation/service-description.html
- SDIT-792: 📝 Document how to find out individual role
- SDIT-792: 📝 Reformat html file
> SDIT-792: 📝 Document how to find out individual role
