src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerSearchResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonSearch.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerSearchService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/SearchOperations.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/MessageIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/QueueIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/GlobalSearchResourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerSearchResourceTest.kt
This is the first of a couple of PRs to introduce a variant of the `/match` endpoint that takes multiple prison ids to search across (to cater for the use case of searching across all of a user's caseloads for example).
This first PR converts the existing endpoint to use the new search functionality, just as a list of one.
=> ♻️ PPD-46: Refactor to make room for search that takes list of prison ids

helm_deploy/prisoner-offender-search/templates/deployment.yaml
Namespace LimitRange set to much higher CPU limit of 2000ms - java now starts much faster so tightening up the liveness/readiness probes.
=> Faster JVM startup. 

helm_deploy/prisoner-offender-search/templates/_envs.tpl, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/config/ElasticSearchConfiguration.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/config/LocalStackConfig.kt, src/test/resources/application-test.yml
This is to make it easier to consume the elasticsearch URL Kubernetes secrets
=> DT-1372 Switch to single elasticsearch URL instead of parts

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerDetailResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerKeywordResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/KeywordService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerDetailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/KeywordSearchResourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerDetailResourceTest.kt
This PR 
* Fixes a couple of issues with keyword and prisoner-detail searches when mixed-case search terms are presented & introduces some test cases to verify these are now handled ok.  
* Updates the Swagger descriptions for keyword and prisoner detail searches.
* Fixes a bug where search terms were not correctly split for keyword searches.
=> AR-1392: Handling mixed-case search terms + tests to verify

.circleci/config.yml
Use the full localstack image with elasticsearch pre-installed to workaround errors we have seen installing elasticsearch on localstack.
=> DT-2295 elasticsearch full

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerDetailService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/dto/PrisonerDetailRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerDetailResourceTest.kt
Existing prisoner detail search will continue to search across prisoner aliases when searching on first name or last name however this new optional attribute will allow this alias check to be disabled.
=> PPD-331 - add flag to allow alias search to be disabled

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/KeywordService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerDetailService.kt
Currently unable to use rest-high-level-client:7.15.2 which come in spring-data-elasticsearch:4.3.0
AWS currently only support elasticsearch to 7.10
https://github.com/elastic/elasticsearch/issues/76091#issuecomment-892817267
=> DT-2959: pinned elasticsearch version 7.12.1

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonersInPrisonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonersInPrisonResourceTest.kt
Unlike the prison-api version this endpoint requires the prisonId and internal location to be supplied separately
=> SDI-254 Added cell location filter (block, wing etc)

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonersInPrisonResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonersInPrisonResourceTest.kt
GLOBAL_SEARCH is for searching across prisoners so created a new role PRISONER_IN_PRISON_SEARCH just for this endpoint. Obviously if a system already has the PRISONER_SEARCH role that can call all endpoints anyway
=> SDI-254 Added new role PRISONER_IN_PRISON_SEARCH 

docker-compose-localstack-tests.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonersInPrisonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonersInPrisonResourceTest.kt
1. Users often leave a comma in the search term `marke, andy` - fix that not returning any searches
2. Output of parameters to application insights
=> SDI-301 Improved auditing and ignored common punctuation

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/Prisoner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
The long term goal is to publish Domain events when a prisoner is updated. By categorising the properties of the Prisoner we can say which kind of properties have changed so consumers can react to changes they are interested in.
=> SDI-287 Create difference engine for Prisoner

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/RestrictedPatientService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
A customEvent with name `POSPrisonerUpdated` is raised listing the properties that have changed in customDimensions.
It should now be possible to query App Insights for recent changes to prisoners in prisoner-offender-search with a query like:
```
customEvents
| where cloud_RoleName == 'prisoner-offender-search'
| where name == 'POSPrisonerUpdated'
| extend offender=tostring(customDimensions.offenderNo)
| where offender == 'A1234AA'
```
Or to find out when a specific property changed, something like:
```
customEvents
| where cloud_RoleName == 'prisoner-offender-search'
| where name == 'POSPrisonerUpdated'
| extend offender=tostring(customDimensions.offenderNo)
| where offender == 'A1234AA'
| where isnotempty(customDimensions.inOutStatus)
```
=> SDI-287 add telemetry for prisoner differences

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
Receive / release of an offender clears many fields in the Elasticsearch Prisoner entity - allow these null fields in Prisoner differences
=> SDI-287 Cater for null differences

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/Prisoner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventEmitter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventsEmitterIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventsEmitterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
* Prisoner updated event changed from `offender.updated` to `prisoner.updated` to align with prison-offender-events naming strategy 
* And `offenderNo` changed to `nomsNumber` to align with POE
* `PropertyType` (used to group changed properties) renamed to `DiffCategory` in the code and `categoriesChanged` in the events
* booking number removed as noms number is the key identifier (booking may or may not exist)
=> SDI-287 refactor

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventEmitter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/integration/IntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventsEmitterIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventsEmitterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt
* Check if the prisoner document on ES has actually changed before sending the prisoner updated domain event
* Stop swallowing exceptions if the domain event fails - allow the exception to percolate so the original prison event is rejected and retried
* Rollback the prisoner hash update if the domain event fails - so the retried prison event is not ignored  and the domain event is sent
=> SDI-287 prevent duplicate events and allow retries

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDifferenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerEventHashRepository.kt, src/main/resources/db/migration/V1_2__prisoner_event_sent.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/integration/IntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventsEmitterIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerDiffServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/diff/PrisonerEventHashRepositoryTest.kt
The `hashCode()` API is only guaranteed to work on the same Java process - no good for distributed computing.
Instead generate a unique hash from the JSON representation of the Prisoner document (as stored in ElasticSearch) to decide whether an updated event has already been published for the prisoner.
=> SDI-287 duplicate prisoner events hash

src/main/resources/application.yml
We tried to increase to 12 pods to have a temporary burst on message handling but hit an AWS limit (error message "FATAL: remaining connection slots are reserved for non-replication superuser connections"). We can increase the number of available connections by increasing the DB Instance size... but this seems overkill as the DB is tiny and traffic is minimal. Therefore I've reduced the connection pool size hopefully freeing up connections to allow more pods.
=> Reduce DB connections to allow more pods

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/translator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerSyncService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/model/TranslatorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerIndexServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/PrisonerSyncServiceTest.kt
Allows a partial update if Incentive  services fails this means main record is updated but the incentive element will remain as previous version - but will retried since message still goes on DLQ
=> SDI-452 Continue with reindex when Incentive failure

helm_deploy/prisoner-offender-search/Chart.yaml, helm_deploy/prisoner-offender-search/values.yaml
During deployment Spring Boot apps need a CPU burst and we've found that sometimes one of the pods isn't given enough CPU by Kubernetes to support this burst and so takes a long time to startup. By using a startup probe we can give the pods a longer window to start without affecting the liveness probe which desn't kick in until the startup probe is finished.
=> SDI-641 Try using a startup probe

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/DomainEventsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/services/HmppsDomainEventEmitter.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/DomainEventsResourceTest.kt
This feature will be used to retrospectively fire domain events after a catastrophic failure.
It will be initially used to create 3 domain events from a failure back in February
=> SDIT-771 Allow ability to manually publish prisoner-offender-search.prisoner.received

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/config/OpenApiConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/GlobalSearchResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PhysicalDetailResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerDetailResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerDifferencesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerKeywordResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonerMatchResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/PrisonersInPrisonResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonersearch/resource/OpenApiDocsTest.kt
In [HMPPS Integration API](https://github.com/ministryofjustice/hmpps-integration-api), we create simulators based on an upstream API's OpenAPI spec using [Prism](https://stoplight.io/open-source/prism) for our smoke tests. Recently we noticed it was failing.
Upon investigation, we realised that security requirements for endpoints within Prisoner Offender Search referred to security schemes that don't exist. This meant that in the Swagger Docs, no "available authorizations" showed for the
endpoint and the OpenAPI spec JSON was invalid (checked by copying it into [Swagger Editor](https://editor.swagger.io/)).
It seems a [recent change in Prism](https://github.com/stoplightio/prism/blob/master/CHANGELOG.md#540-20231009) meant that it doesn't like when invalid [security …
=> HIA-553: 🐛 Fix invalid Swagger docs security schemes for endpoints
